# Generated by Django 4.2 on 2023-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_alter_attendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(),
        ),
    ]
